name: "djf_rgbnir256_gaussion25_adam_0_0.9"


model:
  cnn_t:
    num_conv: 3
    c_in: 3
    c_out: 3
    channel: [96,48,3]
    kernel_size: [9,1,5]
    stride: [1,1,1]
    padding: [2,2,2]

  cnn_g:
    num_conv: 3
    c_in: 3
    c_out: 3
    channel: [96,48,3]
    kernel_size: [9,1,5]
    stride: [1,1,1]
    padding: [2,2,2]

  cnn_f:
    num_conv: 3
    c_in: 6
    c_out: 3
    channel: [64,32,3]
    kernel_size: [9,1,5]
    stride: [1,1,1]
    padding: [2,2,2]


loss:
  name: "l2"


dataset:
  name: "RGB-NIR"
  input_size: [256, 256]
  # train:
  #   target: /data/zf/gan/yxf/new_data/gauss50/noise/
  #   guide: /data/zf/gan/yxf/new_data/gauss50/cut/
  #   gt: /data/zf/gan/yxf/new_data/gauss50/ori/

  # val:
  #   target: /data/zf/gan/yxf/new_data/div/noise/
  #   guide: /data/zf/gan/yxf/new_data/valid_div2k/
  #   gt: /data/zf/gan/yxf/new_data/div/ori/

  # test:
  #   target: /data/zf/gan/yxf/new_data/div/noise/
  #   guide: /data/zf/gan/yxf/new_data/valid_div2k/
  #   gt: /data/zf/gan/yxf/new_data/div/ori/

  generate_noise: True
  noise_sigma: 25

  train:
    target: /data/pzq/RGB-NIR/tiff2png/train/noise/
    guide: /data/pzq/RGB-NIR/tiff2png/train/nir/
    gt: /data/pzq/RGB-NIR/tiff2png/train/rgb/

  val:
    target: /data/pzq/RGB-NIR/tiff2png/test/noise/
    guide: /data/pzq/RGB-NIR/tiff2png/test/nir/
    gt: /data/pzq/RGB-NIR/tiff2png/test/rgb/

  test:
    target: /data/pzq/RGB-NIR/tiff2png/test/noise/
    guide: /data/pzq/RGB-NIR/tiff2png/test/nir/
    gt: /data/pzq/RGB-NIR/tiff2png/test/rgb/


device: cuda


trainer:
  batch_size: 16
  max_iters: 1e5
  lr: 1e-4
  beta1: 0.0
  beta2: 0.9
  # momentum: 1e-5


tester:
  batch_size: 1
  


verbose: True
html: True
seed: 7
log_interval: 100
eval_interval: 5000
test_interval: 5000
sample_interval: 5000
save_interval: 5000
save_path: outputs
ckpt_path: checkpoints
samples_path: samples
outputs_path: results
sample_size: 8
